CREATE TABLE `gcash_log` (
  `objid` varchar(50) NOT NULL,
  `poid` varchar(50) NOT NULL,
  PRIMARY KEY (`objid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
;

INSERT INTO `payment_partner` (`objid`, `name`, `code`, `actionurl`, `caption`, `info`, `allowsend`, `allowpay`, `state`, `requirecheckout`) VALUES ('GCASH', 'GCASH', '104', 'https://api-sit.saas.mynt.xyz/gcash/acquiring/order/create.htm', 'GCASH', '[\r\n    successurl: \"http://192.168.1.202:90/payoptions/gcashsuccess\", \r\n    errorurl: \"http://192.168.1.202:90/payoptions/gcasherror\",\r\n    notificationurl: \"https://www.filipizen.com/webhooks/gcash\",\r\n    wallet: [\r\n        actionurl: \'https://api-sit.saas.mynt.xyz/gcash/acquiring/order/create.htm\',\r\n        headerpost: [\r\n            \'Content-Type\': \'application/json\'\r\n        ],\r\n        headerget: [\r\n            \'Content-Type\': \'application/json\'\r\n        ],\r\n        head:[\r\n            version: \'2.0\',\r\n            function: \'gcash.acquiring.order.create\',\r\n            clientId: \'2021041611312600014799\',\r\n            clientSecret: \'20210416113126000147990IDjS1\',\r\n        ],\r\n        body: [\r\n            merchantId: \'217020000647088090758\', \r\n            productCode: \'51051000101000100001\',\r\n            subMerchantId: \'\',\r\n            subMerchantName: \'TEST LGU\',\r\n            envInfo: [orderTerminalType: \'WAP\', terminalType: \'WAP\'],\r\n        ]\r\n    ]\r\n]\r\n\r\n', '1', '1', 'ACTIVE', '1');
INSERT INTO `payment_partner_option` (`objid`, `partnerid`, `paypartnerid`, `info`) VALUES ('000_GCASH', '000', 'GCASH', '[\r\n    successurl: \"http://192.168.1.202:90/payoptions/gcashsuccess\", \r\n    errorurl: \"http://192.168.1.202:90/payoptions/gcasherror\",\r\n    notificationurl: \"https://www.filipizen.com/webhooks/gcash\",\r\n    wallet: [\r\n        actionurl: \'https://api-sit.saas.mynt.xyz/gcash/acquiring/order/create.htm\',\r\n        headerpost: [\r\n            \'Content-Type\': \'application/json\'\r\n        ],\r\n        headerget: [\r\n            \'Content-Type\': \'application/json\'\r\n        ],\r\n        head:[\r\n            version: \'2.0\',\r\n            function: \'gcash.acquiring.order.create\',\r\n            clientId: \'2021041611312600014799\',\r\n            clientSecret: \'20210416113126000147990IDjS1\',\r\n        ],\r\n        body: [\r\n            merchantId: \'217020000647088090758\', \r\n            productCode: \'51051000101000100001\',\r\n            subMerchantId: \'\',\r\n            subMerchantName: \'TEST LGU\',\r\n            envInfo: [orderTerminalType: \'WAP\', terminalType: \'WAP\'],\r\n        ]\r\n    ]\r\n]\r\n\r\n');

